[plugins]
archloom = { id = "dev.architectury.loom", version = "1.2-SNAPSHOT" }
vineflower = { id = "io.github.juuxel.loom-vineflower", version = "1.11.0" }

[libraries]
jetbrains_annotations = { module = "org.jetbrains:annotations", version = "24.0.1" }
minecraft = { module = "com.mojang:minecraft", version = "1.20.1" }
parchment = { module = "org.parchmentmc.data:parchment-1.20.1", version = "2023.09.03" }

fabric_loader = { module = "net.fabricmc:fabric-loader", version = "0.14.21" }
fabric_api = { module = "net.fabricmc.fabric-api:fabric-api", version = "0.88.1+1.20.1" }